apiVersion: v1
kind: Service
metadata:
  name: thanos-query
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: thanos-query
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
spec:
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      containers:
      - name: thanos-query
        image: quay.io/thanos/thanos:v0.32.5
        args:
        - query
        - --http-address=0.0.0.0:9090
        # Point to the receiver's GRPC port
        - --store=thanos-receive-0.thanos-receive.default.svc.cluster.local:10901

